title: Mehran Amiri
description: Machine Learning Engineer / Senior Software Engineer
theme: sproogen/modern-resume-theme
skin: default
email: meam64@gmail.com
linkedin_username: mehran-amiri-172ba454
github_username: mehi64

name: Mehran Amiri
location: Hildesheim, Lower Saxony, Germany
about: Machine learning engineer with strong background in Math and Statistics. I am a senior software developer as well with 10 years of experience.

sections:
  - title: Experience
    layout: list
    content:
      - title: Head of the Software Team
        company: Hybrid LiDAR Systems AG
        dates: 2019 - Present
        description: To be added later

  - title: Education
    layout: list
    content:
      - title: M.S. in Data Analytics
        institution: Hildesheim University

  - title: Skills
    layout: text
    content: AI/ML, Agile, Scrum, SQL, Business Foundations

  - title: Certifications
    layout: list
    content:
      - title: PMI‑PBA®
      - title: PSPO I®

  - title: Languages
    layout: text
    content: English, Persian, German, C++, Python, Java
